services:
  chatbot: 
    image: chatpdf-chat:latest
    command: npm start
    # volumes:
    #   - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=chatbot
      - DB_USER=chatbot
      - DB_PASS=chatbot
  api:
    image: chatpdf-api:latest
    command: python app.py
    # volumes:
    #   - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "8000:8000"